[TOC]

# 异常处理

```cpp
    try	尝试堆代码进行运行,如果是正常处理,和一般的执行是一样的,如果有错误,会报错
    {
    	throw 123;   
	}
    catch (int e)
    {
	}
    catch (bool e)
    {
        
    }



int main()
{	
    throw 123;//用于抛出指定类型的异常,抛出的异常和报错类型一致
    throw "123";
    struct  test
    {
        
    }
    throw test();
        
        
        
    return 0;
}
```

## 使用场景

把错误转移到外界处理,给拯救程序的机会

比如我们学的vector,用下标越界,使用release,不会报错,但程序运行会挂掉

但是有个问题,我们必须知道异常的类型

```cpp
std::vector<int> a = {1,2,3};
a[10000] = 456;		//release不会报错
a.at(10000) = 456//release会有报错
```

## 使用不定参抓异常

可以抓取任何异常,保证程序正常失败;

```cpp
catch(...)
{
    printf("有未知的异常类型");
}
```

# 异常类

推荐自己写的程序,都有个异常类,方便获取异常,然后可以写入错误日志文件里.

但是不好的地方在于降低程序性能,最好只在开发时使用,不要滥用;
